Name: Starter Workflow Demo

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      

      
      - run: echo This is a demo start workflow
